### ISSUE TITLE
 [ERROR] Class "Rector\Core\Rector\AbstractRector" not found                 

### ISSUE THREAD

**Issue by carloss1989** [remarkablemark/rector-laravel-database-expressions#34]
![Captura de pantalla 2024-02-20 a las 11 34 46 a  m](https://github.com/remarkablemark/rector-laravel-database-expressions/assets/137532524/2263412a-e58d-45f0-af4f-3d720a3eb1b3)

**Comment by remarkablemark** [comment]
@carloss1989 can you provide a reproducible repo?

**Comment by remarkablemark** [comment]
This should be fixed in:

- https://github.com/remarkablemark/rector-laravel-database-expressions/pull/38#issuecomment-1963476365
